server:
  port: 8080
feature:
  jms: true
  stream: true
spring:
  application:
    name: stream
  activemq:
    broker-url: tcp://localhost:61616
    # user:
    # password:
    packages:
      trust-all: true
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        in:
          destination: stream
          group: group
        out:
          destination: stream
          group: group